name: Build and test lab-cicd

on:
  # Automatically run this pipeline on every push to the main branch
  push:
    branches:
      - main
  # Allow running this pipeline manually from GitHub's website
  workflow_dispatch:

jobs:
  test:
    name: Test cicd-lab
    runs-on: ubuntu-22.04
    steps:
      # Checkout our repository
      - uses: actions/checkout@v4

      # Install our NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Run our unit tests
      - name: Run unit tests
        run: npm run test

  build:
    name: Build cicd-lab
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      GITHUB_USER: nissebergman
      IMAGE_REGISTRY: ghcr.io/nissebergman
      
    steps:
      # Checkout our repository
      - uses: actions/checkout@v4

      # Setup Docker with BuildKit
      - uses: docker/setup-buildx-action@v3

      # Login to our container registry
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build and push container image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/lab-cicd:${{ env.SHA_SHORT }}
            ${{ env.IMAGE_REGISTRY }}/lab-cicd:latest
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
